using Dashboard.API.Domain.Enums;

namespace Dashboard.API.Domain.Entities
{
    public class JobApplication
    {
        // we are adopting a Domain-Driven Design (DDD) approach, so we guarantee that an instance of a class CANNOT be created in an invalid state.
        // this will make database more consistent
        // in case of validation errors, we will throw an exception
        // validation(server side) should be already done in api/application layer by fluent validation

        public int Id { get; private set; } // auto-incremented primary key

        public string Name { get; private set; } = string.Empty; //entered by user

        public string Email { get; private set; } = string.Empty; //entered by user

        public string JobTitle { get; private set; } = string.Empty; //entered by user

        public StatusEnum Status { get; private set; }// set automatically by system

        public DateTime CreatedAt { get; private set; }// set automatically by system

        private JobApplication()
        { } // for the EF Core

        public static JobApplication Create(
            string name,
            string email,
            string jobTitle
            )
        {
            ValidateName(name);
            ValidateEmail(email);
            ValidateJobTitle(jobTitle);
            return new JobApplication
            {
                //Id auto generated by database
                Name = name,
                Email = email,
                JobTitle = jobTitle,
                Status = StatusEnum.New,
                CreatedAt = DateTime.UtcNow
            };
        }

        private static void ValidateName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Name cannot be null or empty.");

            if (name.Length < 2 || name.Length > 100)
                throw new ArgumentException("Name must be between 2 and 100 characters long.");
        }

        private static void ValidateEmail(string email)
        {
            if (string.IsNullOrWhiteSpace(email))
                throw new ArgumentException("Email cannot be null or empty.");

            if (email.Length < 5 || email.Length > 100)
                throw new ArgumentException("Email must be between 5 and 100 characters long.");

            if (!email.Contains("@"))
                throw new ArgumentException("Email must contain '@' symbol.");
        }

        private static void ValidateJobTitle(string jobTitle)
        {
            if (string.IsNullOrWhiteSpace(jobTitle))
                throw new ArgumentException("Job title cannot be null or empty.");

            if (jobTitle.Length < 2 || jobTitle.Length > 100)
                throw new ArgumentException("Job title must be between 2 and 100 characters long.");
        }

        public void MakeInProgress()
        {
            if (Status != StatusEnum.New)
            {
                throw new InvalidOperationException("Cannot make job application in progress unless it is in the 'New' state.");
            }
            Status = StatusEnum.InProgress;
        }

        public void MakeDone()
        {
            if (Status != StatusEnum.InProgress)
            {
                throw new InvalidOperationException("Cannot mark job application as done unless it is in the 'InProgress' state.");
            }
            Status = StatusEnum.Done;
        }
    }
}