namespace Dashboard.API.Application.DTOs.RequestDTOs
{
    public class CreateJobApplicationRequestDTO
    {
        //here we are making fields nullable to make FluentValidation handle all the validation rules,
        //and Swagger will show fluent validation rules only

        //Id,status,createdAt is autogenerated by the system
        public string? Name { get; set; }

        public string? Email { get; set; }

        public string? JobTitle { get; set; }
    }
}